language: android
before_install:
    - wget http://services.gradle.org/distributions/gradle-1.12-all.zip
    - unzip gradle-1.12-all.zip
    - export GRADLE_HOME=$PWD/gradle-1.12
    - export PATH=$GRADLE_HOME/bin:$PATH
script: 'gradle build'
android:
    componenents:
        - build-tools-21.0.2
        - android-21
        - extra-android-support
        - extra-android-m2repository
